const themeConfig = {
  templateName: 'KATALOG OBAT v2',
  buildVersion: 'v2.0.0-Admin',
  backVersion: 'v2.0.0-Client',
  layout: 'vertical',
  mode: 'light',
  direction: 'ltr',
  skin: 'default',
  contentWidth: 'boxed',
  footer: 'static',
  routingLoader: true,
  navHidden: true,
  menuTextTruncate: true,
  navSubItemIcon: 'mdi:circle-outline',
  verticalNavToggleType: 'accordion',
  navCollapsed: false,
  navigationSize: 260,
  collapsedNavigationSize: 68,
  afterVerticalNavMenuContentPosition: 'fixed',
  beforeVerticalNavMenuContentPosition: 'fixed',
  horizontalMenuToggle: 'hover',
  horizontalMenuAnimation: true,
  appBar: 'fixed',
  appBarBlur: true,
  responsiveFontSizes: true,
  disableRipple: false,
  disableCustomizer: false,
  toastPosition: 'top-right'
}

export default themeConfig
